### ISSUE TITLE
Sprite concept not working V9958

### ISSUE THREAD

**Issue by EMLommers** [hra1129/msx_documents#1]
I tried your concept on MSX2+, but it is not working like theoretically suggested.
Still maximum is 8 per line, without blinking or half sprites.

Is there some error? Or is it not working on V9938 and V9958?
My test code:
[SPRITE.ASM.TXT](https://github.com/hra1129/msx_documents/files/11403196/SPRITE.ASM.TXT)

**Comment by hra1129** [comment]
Am I correct in understanding that this point relates to the following PDF?

https://github.com/hra1129/msx_documents/tree/main/vdp/sprite_sample

And, if you mean 8 horizontal sprites, are you using Sprite Mode 2?

In the case of Sprite Mode 2, the sprite color does not exist in the attribute table, so a separate sprite color table must be set up.
I don't see any part of your code that sets the sprite color table.

**Comment by EMLommers** [comment]
I am using screen 5
and just 23 block of 16x16,
correct the color does not exist, neglect able
Sprite color tbale was not really priority, becasue I just wanted to see 32 same sprites on 1 line.
What did I do wrong?.

**Comment by hra1129** [comment]
Once the game I am working on is settled, I will make and place a sample program.
Until then, please wait a little.

**Comment by EMLommers** [comment]
New file
still not working...
new file: 
[sprite.asm.txt](https://github.com/hra1129/msx_documents/files/11465313/sprite.asm.txt)
(updated May 12:16:47)

In 16x16 mode the sprite number I used was still 0-32 but had to use 0 3 7 etc.
Also, If I would create 2 or more line interrupts (R19) and switch vdp r#5 and R#6 to other location, where also sprite data exist and use your technique, would it possible to show 32 sprites* line interrupts (if speed of z80 and vdp would allow)
I do not know whether you have tested this already 
If line interrupts are 32 high and on one 1 line possible to put 16 in OR, 8 (16)sprites on line, 16 (32) in 2 lines (32 high).... and 4 times..... results in a big colored sprite of 128 x 128 pixels..... in multicolor
Moving sprite up and down by changing x and y and the line interrupt line number
Or is this thinking tooo much to wish for..

**Comment by hra1129** [comment]
https://github.com/hra1129/msx_documents/tree/main/vdp/sprite_sample/sprite_mode2

**Comment by hra1129** [comment]
Here is a summary of how to deal with the problem of disappearing when 9 or more pieces are lined up horizontally.
The method to realize "displaying more than 32 sprites," commonly called "sprite doubler," is not mentioned here.

The solution to the disappearing problem has been demonstrated in the above sample, which also works with V9938, so this matter is closed.
